server.port=4000

spring.datasource.url=jdbc:postgresql://localhost:5432/homespace
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD_HERE
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowedOrigin=http://localhost:5174
